/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mic_jnibase_NativeLib */

#ifndef _Included_com_mic_jnibase_NativeLib
#define _Included_com_mic_jnibase_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
#undef com_mic_jnibase_NativeLib_A
#define com_mic_jnibase_NativeLib_A 100L

#undef com_mic_jnibase_NativeLib_MODE_NORMAL
#define com_mic_jnibase_NativeLib_MODE_NORMAL 0L
#undef com_mic_jnibase_NativeLib_MODE_LUOLI
#define com_mic_jnibase_NativeLib_MODE_LUOLI 1L
#undef com_mic_jnibase_NativeLib_MODE_DASHU
#define com_mic_jnibase_NativeLib_MODE_DASHU 2L
#undef com_mic_jnibase_NativeLib_MODE_JINGSONG
#define com_mic_jnibase_NativeLib_MODE_JINGSONG 3L
#undef com_mic_jnibase_NativeLib_MODE_GAOGUAI
#define com_mic_jnibase_NativeLib_MODE_GAOGUAI 4L
#undef com_mic_jnibase_NativeLib_MODE_KONGLING
#define com_mic_jnibase_NativeLib_MODE_KONGLING 5L
/*
 * Class:     com_mic_jnibase_NativeLib
 * Method:    changeName
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mic_jnibase_NativeLib_changeName
  (JNIEnv *, jobject);

/*
 * Class:     com_mic_jnibase_NativeLib
 * Method:    changeAge
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mic_jnibase_NativeLib_changeAge
  (JNIEnv *, jclass);

/*
 * Class:     com_mic_jnibase_NativeLib
 * Method:    callAddMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mic_jnibase_NativeLib_callAddMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_mic_jnibase_NativeLib
 * Method:    testArrayAction
 * Signature: (ILjava/lang/String;[I[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mic_jnibase_NativeLib_testArrayAction
  (JNIEnv *, jobject, jint, jstring, jintArray, jobjectArray);

/*
 * Class:     com_mic_jnibase_NativeLib
 * Method:    putObject
 * Signature: (Lcom/mic/jnibase/Student;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mic_jnibase_NativeLib_putObject
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_mic_jnibase_NativeLib
 * Method:    insertObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mic_jnibase_NativeLib_insertObject
  (JNIEnv *, jobject);

/*
 * Class:     com_mic_jnibase_NativeLib
 * Method:    testQuote
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mic_jnibase_NativeLib_testQuote
  (JNIEnv *, jobject);

/*
 * Class:     com_mic_jnibase_NativeLib
 * Method:    delQuote
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mic_jnibase_NativeLib_delQuote
  (JNIEnv *, jobject);

/*
 * Class:     com_mic_jnibase_NativeLib
 * Method:    voiceChangeNative
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mic_jnibase_NativeLib_voiceChangeNative
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
