/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mic_jnibase_NativeLib_FmodCallback */
//无用的类
#ifndef _Included_com_mic_jnibase_NativeLib_FmodCallback
#define _Included_com_mic_jnibase_NativeLib_FmodCallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
