/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string>
/* Header for class com_mic_jnibase_NativeLib */

// 解决循环Copy的问题 第二次就进不来了
#ifndef _Included_com_mic_jnibase_NativeLib// 如果没有定义这个宏
#define _Included_com_mic_jnibase_NativeLib // 我就定义这个宏

#ifdef __cplusplus// 如果是C++环境
extern "C" {// 全部采用C的方式 不准你函数重载，函数名一样的问题
#endif
#undef com_mic_jnibase_NativeLib_A
#define com_mic_jnibase_NativeLib_A 100L
/*
 * Class:     com_mic_jnibase_NativeLib
 * Method:    changeName
 * Signature: ()V
 */
// 函数的声明
JNIEXPORT void JNICALL Java_com_mic_jnibase_NativeLib_changeName
  (JNIEnv *, jobject);

/*
 * Class:     com_mic_jnibase_NativeLib
 * Method:    changeAge
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mic_jnibase_NativeLib_changeAge
  (JNIEnv *, jclass);

/*
 * Class:     com_mic_jnibase_NativeLib
 * Method:    callAddMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mic_jnibase_NativeLib_callAddMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus// 省略  如果是C++，啥事不干
}
#endif
#endif
