/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mic_jnibase_DParcel_MyObject */

#ifndef _Included_com_mic_jnibase_DParcel_MyObject
#define _Included_com_mic_jnibase_DParcel_MyObject
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
