/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mic_jnibase_NativeLib_UpdateUiCallback */

#ifndef _Included_com_mic_jnibase_NativeLib_UpdateUiCallback
#define _Included_com_mic_jnibase_NativeLib_UpdateUiCallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
