[auth]
#这个appid对应就是aiui的appid，需要进行修改，其他选项不需要动
appid=564eb8ad

rsa_pub= /vtn/publicKey.pem
rsa_pri= /vtn/privateKey.pem

[cae]
#是否开启降噪功能, 0为不开启，其他为开启，默认为开启
cae_enable = 1
#beam取值说明: -2 表示不输出任何音频, -1 第四路为识别音频，无第五路,
#0，1，2时，第四路为指定波束的音频，第五路为vad音频
beam = 1
input_audio_unit=4

[ivw]
#是否开启唤醒功能, 0为不开启，其他为开启，默认为不开启
ivw_enable = 1
ivw_num = 1

#唤醒资源
res_path= /vtn/one_ivw.3.13.1.bin

vtn_ini_path = /vtn/vtn.ini
